# Generated by Django 5.2.1 on 2025-05-17 21:57

import django.db.models.deletion
import projects.models
import storages.backends.s3
import thumbnails.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(help_text='Upload video files only (MP4, MOV, AVI, etc.)', storage=storages.backends.s3.S3Storage(access_key='AKIA2FI4LTDDZFSJPDFJ', bucket_name='topresource', default_acl='private', file_overwrite=True, location='media', region_name='us-east-1', secret_key='JGYm+/egNdJ24ZneMArVRLyFxd08jKZbCU521iNf'), upload_to='videos/', validators=[projects.models.validate_video_file])),
                ('thumbnail', thumbnails.fields.ImageField(blank=True, null=True, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.tag')),
                ('featured_video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.video')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
