# Generated by Django 5.2.1 on 2025-05-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='ProjectType',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tags',
            new_name='project_type',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
