# Generated by Django 5.2.1 on 2025-05-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_tag_projecttype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='uploaded_at',
            new_name='created',
        ),
    ]
