# Generated by Django 5.2.1 on 2025-05-19 17:25

import projects.models
import thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_uploaded_at_video_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_video',
            field=models.FileField(default='default-video.mp4', help_text='Upload video files only (MP4, MOV, AVI, etc.)', upload_to='videos/', validators=[projects.models.validate_video_file]),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='projecttype',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=thumbnails.fields.ImageField(blank=True, default='thumbnails/default-video.png', null=True, upload_to='thumbnails/'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
