# Generated by Django 5.2.1 on 2025-05-19 17:25

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_featured_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_video',
            field=models.FileField(default='videos/default-video.mp4', help_text='Upload video files only (MP4, MOV, AVI, etc.)', upload_to='videos/', validators=[projects.models.validate_video_file]),
        ),
    ]
