# Generated by Django 5.2.1 on 2025-05-21 15:03

import django.db.models.deletion
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_featured_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projecttype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='thumbnails/default-video.png', null=True, upload_to='thumbnails/'),
        ),
    ]
