# Generated by Django 5.2.1 on 2025-05-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_project_date_project_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='project_type',
        ),
    ]
